name: 'UC4 Dev_Network Setup'
description: 'Sets up the UC4 Dev-Network'

inputs:
  network_folder:
    description: 'path to the network where we can find the network.sh script.'
    required: true
    default: 'hlf-dev-network'
  chaincode_branch:
    description: 'branch of the chaincode repo you want to checkout.'
    required: true
    default: ''

runs:
    using: "composite"
    
    steps:    
    # set up Dev_network
    - name: Set up dev_network - dockers
      run: |
        pushd ./${{ inputs.network_folder }}
        echo "##########################"
        echo "#  start network script  #"
        echo "##########################"
        ./startNetwork.sh ${{ inputs.chaincode_branch }} &
        echo "##########################"
        echo "# started network script #"
        echo "##########################"
        echo "#    begin sleep         #"
        echo "##########################"
        sleep 100
        echo "#    finish sleep        #"
        echo "##########################"
        popd
      shell: bash
