name: 'UC4 Production Network setup'
description: 'Sets up the UC4 Production Network'

inputs:
  network_folder:
    description: 'path to the network where we can find the startNetwork.sh and installChaincode.sh scripts.'
    required: true
    default: 'hlf-network'
  chaincode_branch:
    description: 'branch of the chaincode repo you want to checkout.'
    required: true
    default: 'develop'

runs:
    using: "composite"
    
    steps:    
    # start network
    - name: Start Network
      run: |
        pushd ${{ inputs.network_folder }}
        echo "##########################"
        echo "#  start deploy script   #"
        echo "##########################"
        echo "UC4_KIND_NODE_IP before script = $UC4_KIND_NODE_IP"

        ./deploy.sh -b ${{ inputs.chaincode_branch }} -t
        export NODE_IP=$(source ./scripts/util.sh && get_worker_ip)
        echo "::set-env name=UC4_KIND_NODE_IP::$NODE_IP"
        echo "NODE_IP=$NODE_IP"
        echo "UC4_KIND_NODE_IP=$UC4_KIND_NODE_IP"
        popd
      shell: 
        bash
